Drop support for Python 3.7
Python 3.7 is causing the following error and making it more
time-consuming than necessary to build a test environment.

```
Initializing new virtualenv in /home/runner/work/gribcoder/gribcoder/.venv
Python version: cpython@3.7.9
RuntimeError: failed to query /home/runner/.rye/py/cpython@3.7.9/install/bin/python3 with code 1 err: 'Traceback (most recent call last):\n  File "/home/runner/.rye/self/lib/python3.11/site-packages/virtualenv/discovery/py_info.py", line 12, in <module>\n    import platform\n  File "/home/runner/.rye/py/cpython@3.7.9/install/lib/python3.7/platform.py", line 116, in <module>\n    import sys, os, re, subprocess\n  File "/home/runner/.rye/py/cpython@3.7.9/install/lib/python3.7/subprocess.py", line 152, in <module>\n    import _posixsubprocess\nModuleNotFoundError: No module named \'_posixsubprocess\'\n'
error: failed creating virtualenv ahead of sync

Caused by:
    failed to initialize virtualenv
Error: Process completed with exit code 1.
```

Also, Python 3.7 reached end-of-life on 2023-06-27.